### PR TITLE
In teach/handle channel hidden

### LINKED ISSUE #187: Event channel.hidden doesn't hide the channel from the channel list
Hello,

**Describe the bug**
When a user is a member of a list of channels and one of them is hidden then the current list of channels is not updated to exclude the hidden one.

**Dev environment info (please complete/provide the following information):**

- Package version : stream-chat-react-native 0.10.0-rc.0
- RN : 0.61.5
- iOS simulator 13.3 (type iPhone 11).
- MacOS Catalina

**To Reproduce**
Create a simple One - One channel like this 

backend/index.js
```js
const channel = this._chat.channel("messaging", {
      members: ['thomas', 'eric'],
      created_by_id: 'eric'
    });
```
mobile/index.js

```js
const chatClient = new StreamChat("streamKey");
await chatClient.setUser(
  {
    id: "thomas",
  },
  "token" // -> It's replaced by the real token in my code
);
<Chat
  style={{
    colors: {
      primary: Config.getTheme("mainColor"),
    },
  }}
  client={chatClient}
  i18nInstance={streami18n}
>
    <ChannelList
      filters={{
        type: "messaging",
        members: { $in: ["thomas"] },
      }}
      sort={{ last_message_at: -1 }}
      Preview={ChannelPreviewMessenger}
      LoadingIndicator={() => (
        <ActivityIndicator size="large" color={Config.getTheme("mainColor")} />
      )}
      onSelect={(channel) => {
        Actions.chat({ chatClient, channel, streami18n });
      }}
    />
</Chat>;
```

Later on hide the channel like with the JS SDK 
```js
channel.hide('thomas');
```
**Misc**

I can see in the app the event and I get this in the console.log

```js
{
type: "channel.hidden"
cid: "id" // replaced
created_at: "2020-04-12T13:57:54.907965464Z"
clear_history: false
}
```

Also in [ChannelList.js](https://github.com/GetStream/stream-chat-react-native/blob/master/src/components/ChannelList.js#L335), there is no case for the **channel.hidden** event, so is this a wanted behavior ?

Thanks

### PR DESCRIPTION
**Pull request by Antoine-C**
# Submit a pull request

## CLA

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required).
- [x] The code changes follow best practices
- [ ] Code changes are tested (add some information if not applicable)

## Checklist

- [x]  Channel gets removed from list when channel.hidden is received.
- [x] Introduce a new prop - **onChannelHidden**, which can be used to override default handler, similar to onMessageNew or onChannelTruncated
- [x] Add the new prop **onChannelHidden** to PropType list with little doc.
- [x] Include the new prop to typescript file
- [x] Fix documentation links

## Description of the pull request

This PR fixes #187 by handling the channel.hidden event. Unfortunately I can't test this right now but all I did is take the same method from the channel.deleted event so it should works.

I also fixed the documentation link in PropTypes.

### CODE REVIEW

File: types/index.d.ts [hunk 1]
```diff
@@ -423,6 +423,10 @@ export interface ChannelListProps
     thisArg: React.Component<ChannelListProps>,
     e: Client.Event<Client.ChannelTruncatedEvent>,
   ): void;
+  onChannelHidden?(
+    thisArg: React.Component<ChannelListProps>,
+    e: Client.Event<Client.ChannelTruncatedEvent>,
```
Comment (vishalnarkhede) [inline types/index.d.ts:428]: Change it to `Client.ChannelHiddenEvent`. It doesn't exist in js client yet. I will add it tomorrow :)

Comment (Antoine-C) [reply types/index.d.ts]: Done in 38a08e6

Comment (vishalnarkhede) [reply types/index.d.ts]: Thanks :)

**Comment by vishalnarkhede** [comment]
@Antoine-C changes are published as part of `0.10.1` :)
