### PR TITLE
fix: if camera permission cannot be requested go to settings

### LINKED ISSUE #2047: If user doesn't allow camera permissions, and clicks again on camera - nothing happens
**Describe the bug**

When the user click on the attachment button and presses  the camera button, it prompts the native alert for the user to allow the camera access. But if the user does not allow it and you click again, where is no feedback on that matter (like on image picker when you clikc on the gallery it says: "Allow access to your photos in your gallery" and that redirects to the phone permission settings for that app.

**Dev environment info (please complete/provide the following information):**
IOS

- Package version (stream-chat-react-native/stream-chat-expo)
stream-chat-react-native
- react-native or expo version  
- React native CLI
- Device/Emulator (android/ios) and OS version
IOS

**To Reproduce**

1. Go to chat channel
2. Click on 'attachement (file) button'
3. Click on 'camera icon'
4. DO NOT allow the camera access
5. Click again on the 'camera icon'
6. Nothing happens (modal is off)

**Expected behavior**

6. User should be prompted to open the iPhone settings and give the permissions manually)
7.  Would be nice to copy the logic from the gallery button press 

**Additional context**

**Screenshots**

bb

### PR DESCRIPTION
**Pull request by santhoshvai**
## 🎯 Goal

fixes #2047

## ☑️ Checklist

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] PR targets the `develop` branch
- [ ] Documentation is updated
- [ ] New code is tested in main example apps, including all possible scenarios
  - [ ] SampleApp iOS and Android
  - [ ] Expo iOS and Android

### CODE REVIEW

File: package/expo-package/src/handlers/takePhoto.ts [hunk 1]
```diff
@@ -10,12 +10,17 @@ type Size = {
 export const takePhoto = async ({ compressImageQuality = 1 }) => {
   try {
     const permissionCheck = await ImagePicker.getCameraPermissionsAsync();
-    const permissionGranted =
-      permissionCheck?.status === 'granted'
-        ? permissionCheck
-        : await ImagePicker.requestCameraPermissionsAsync();
+    const canRequest = permissionCheck.canAskAgain;
+    let permissionGranted = permissionCheck.granted;
+    if (!canRequest && !permissionGranted) {
```
Comment (khushal87) [inline package/expo-package/src/handlers/takePhoto.ts:15]: Can we simplify the condition as?

```tsx
if (!permissionGranted) {
  if(canRequest) {
        const response = await ImagePicker.requestCameraPermissionsAsync();
        permissionGranted = response.granted;
  } else {
        Linking.openSettings();
        return { cancelled: true };
  }
} else {
// lines here 
}
```

**Review by khushal87 — CHANGES_REQUESTED** [review]

**Review by khushal87 — APPROVED** [review]
