### PR TITLE
fix: sample app ui bugs

### LINKED ISSUE #1682: Creating new group chat doesn't have all the added members.
**Describe the bug**
See video please / Title.  

**Dev environment info (please complete/provide the following information):**
Cloned the latest version as of this repo aug 25th 2022. 

**To Reproduce**
1. Press the new chat icon. 
2. Choose someone that you have not had a 1v1 conversation first and then add other members
3. Send a message to the group
4. You will see that not all added members are there. 

Also (another small issue) you can see at the end of the video that the selected user's state isn't cleared after the group chat is made.  

**Additional context**
It seems like the channel component is not re-rendering. Because of this, I think it has the old channel from its channel prop and thus creates a group chat from the old channel, maybe?

https://user-images.githubusercontent.com/12666226/186730440-de35c54f-dba1-497f-b849-f4d057dc6201.mp4

### PR DESCRIPTION
**Pull request by khushal87**
Fixes #1682, #1506 and a couple of other bugs reported here - https://getstream.slack.com/archives/C02EK5GMU8Z/p1734357005740019

### CODE REVIEW

File: examples/SampleApp/src/components/UserInfoOverlay.tsx [hunk 1]
```diff
@@ -302,14 +302,24 @@ export const UserInfoOverlay = (props: UserInfoOverlayProps) => {
                               members,
                             });
 
-                            const newChannel =
-                              channels.length === 1
-                                ? channels[0]
-                                : client.channel('messaging', {
-                                    members,
-                                  });
+                            console.log('channels', channels.length);
```
Comment (isekovanic) [inline examples/SampleApp/src/components/UserInfoOverlay.tsx:305]:
```suggestion
```

Comment (khushal87) [reply examples/SampleApp/src/components/UserInfoOverlay.tsx]: Thanks :)
