### PR TITLE
fix: remove return null check from OverlayProvider and Chat component

### LINKED ISSUE #2037: First Render Always Blank
**Describe the bug**
The `OverlayProvider` blocks rendering content on the very first render because it starts registering the language in a useEffect in the `useStreami18n` hook. Initially we had the OverlayProvider wrap a react navigation stack (since we had multiple screens with your UI components). But because the user would see a white flash when navigating to this stack, we decided to wrap each individual screen content instead. You still see a white flash in the content area, but at least the screen headers render right away. 

I think this could be done sooner and not have to wait for the component to mount. Or at least provide a loader to render in its place if this cannot be avoided.

| OverlayProvider | useStreami18n |
| ------ | ------ |
|    image    |    image  |

**Dev environment info (please complete/provide the following information):**

- Package version stream-chat-react-native@5.12.1-beta.1
- react-native
- Device/Emulator: Android and IOS

**To Reproduce**

1. Render any content within the OverlayProvider and see you get a flash of blank content on first render.

**Expected behavior**
Content should render right away, or have placeholder content (like a loader) instead.

**Screenshots**
Screenshots above. 

Here is a video as well when we had the navigation header wrapped in the OverlayProvider. See the delayed render going to the Messages screen:

https://user-images.githubusercontent.com/115643473/229585359-60fcae28-6b2d-48ca-8e4b-96d7fde549dc.mp4

### PR DESCRIPTION
**Pull request by khushal87**
## 🎯 Goal

Fixes #2037 

## 🎨 UI Changes

<details>
<summary>iOS</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

<details>
<summary>Android</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

## ☑️ Checklist

- [x] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [x] PR targets the `develop` branch
- [ ] Documentation is updated
- [x] New code is tested in main example apps, including all possible scenarios
  - [x] SampleApp iOS and Android
  - [x] Expo iOS and Android

### CODE REVIEW

File: package/src/hooks/useStreami18n.ts [hunk 1]
```diff
@@ -12,7 +12,6 @@ export const useStreami18n = ({
   setTranslators: React.Dispatch<React.SetStateAction<TranslatorFunctions>>;
   i18nInstance?: Streami18n;
 }) => {
-  const [loadingTranslators, setLoadingTranslators] = useState(true);
   const isMounted = useIsMountedRef();
```
Comment (santhoshvai) [inline package/src/hooks/useStreami18n.ts:15]:
```suggestion
```

seems unused

**Comment by santhoshvai** [comment]
Also, I think it is a good idea to remove some parts from useEffect so that it happens during render  and not after the render maybe using usememo or bringing the translators state inside.. this whole hook seems badly done in the first place in my view 😢 
 
 I am talking about the following parts
 
   ```
    let streami18n: Streami18n;

    if (i18nInstance instanceof Streami18n) {
      streami18n = i18nInstance;
    } else {
      streami18n = new Streami18n({ language: 'en' });
    }

     streami18n.getTranslators().then((translator) => {
      if (translator && isMounted.current) setTranslators(translator);
    });
    ```
    
    There is no reason to run the promise after the render actually if you think about it.. What say?

**Comment by khushal87** [comment]
I have moved the translator state inside, because it makes sense to me.

File: package/src/hooks/useStreami18n.ts [hunk 2]
```diff
@@ -28,20 +31,21 @@ export const useStreami18n = (
...
       });
+
     const { unsubscribe: unsubscribeOnTFuncOverrideListener } =
       streami18n.addOnTFunctionOverrideListener((t) => {
         updateTFunction(t);
       });
+
     streami18n.getTranslators().then((translator) => {
       if (translator && isMounted.current) setTranslators(translator);
     });
```
Comment (santhoshvai) [inline package/src/hooks/useStreami18n.ts:42]: this I think can be moved out of useEffect.. because there is no unsubscribe needed here..

So with useEffect this essentially runs after render rather than before render.. 

I hope it makes sense

File: package/src/components/Chat/Chat.tsx [hunk 3]
```diff
@@ -226,8 +217,6 @@ const ChatWithContext = <
     enableOfflineSupport,
   });
 
-  if (loadingTranslators) return null;
```
Comment (vishalnarkhede) [inline package/src/components/Chat/Chat.tsx:229]: Make sure to test it by adding some delays to `streami18n.getTranslators()` method. Just to make sure whats the behavior when `translators` is not ready

**Review by vanGalilea — APPROVED** [review]
