### PR TITLE
fix: add latest version >11.2.6 compatibility for op-sqlite

### LINKED ISSUE #2891: [🐛] Bug Report no such table: userSyncStatus error if offline support is on and op-sqlite package is updated
## Issue

When we received an update for the **@op-engineering/op-sqlite** package, an error occurred while retrieving Application settings: Error occurred: Query failed: Error: [op-sqlite] sqlite query error: **no such table: userSyncStatus: error**

### Steps to reproduce

1. Upgrade @op-engineering/op-sqlite > 11.2.5
2. Build and open app

### Offline support

- [X] I have enabled offline support.
- [X] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

- **Platform that you're experiencing the issue on**:
    - [X] iOS
    - [ ] Android
    - [X] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### PR DESCRIPTION
**Pull request by khushal87**
The goal of the PR is to add compatibility for the latest version of op-sqlite. This fixes #2891 as a part of the change. This also includes TS issue fixes.

### CODE REVIEW

File: package/src/store/SqliteClient.ts [hunk 1]
```diff
@@ -75,14 +75,24 @@ export class SqliteClient {
...
       if (!this.db) {
         throw new Error('DB is not open or initialized.');
       }
-      await this.db.executeBatch(queries);
+      // This is a workaround to make the executeBatch method work.
+      // It expects an empty array as the second argument in the individual queries if nothing present.
+      // Discussion - https://discord.com/channels/1301463257722126357/1324262993780932688/1330846910596251711
+      const finalQueries = queries.map((query) => {
+        if (query.length === 1) {
+          // @ts-ignore
```
Comment (isekovanic) [inline package/src/store/SqliteClient.ts:90]: Why do we need to `@ts-ignore` here ?

**Review by isekovanic — APPROVED** [review]

File: package/src/store/SqliteClient.ts (hunk 1 above)
Comment (khushal87) [reply package/src/store/SqliteClient.ts:90]: Already discussed on slack
