### PR TITLE
fix: handle hidden channels in message.new listener

### LINKED ISSUE #1463: Latest Channel with Message do not appear on Channel List when new message is received
**Describe the bug**
When a message is received in a Channel it doesn't load automatically to the top after it's deleted. When 1st user hides the chat(channel) (I am using the .hide() method in channel obj) and after that 2nd user starts messaging to 1st one the chat does not appear to 1st user till he does not update ChannelList(by swiping down the list).

**Dev environment info (please complete/provide the following information):**

Yarn: 1.22.15
Node: 16.15.1

"stream-chat-react-native": "^4.3.1"
"@stream-io/flat-list-mvcp": "^0.10.1",
"stream-chat-test-data-cli": "0.1.0-beta.3",

**To Reproduce**
Shared in this video - https://drive.google.com/file/d/12RyYicIxjJa2te8bn3Zdkstzz-_TqHKT/view

**Expected behavior**
The channel should load automatically to the top.

**Additional context**
NIL

**Screenshots**
Check the video above.

### PR DESCRIPTION
**Pull request by vishalnarkhede**
## 🎯 Goal

Fixes #1463 

## 🎨 UI Changes

<details>
<summary>iOS</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

<details>
<summary>Android</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

## ☑️ Checklist

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] PR targets the `develop` branch
- [ ] Documentation is updated
- [ ] New code is tested in main example apps, including all possible scenarios
  - [ ] SampleApp iOS and Android
  - [ ] Expo iOS and Android

### CODE REVIEW

File: package/src/components/ChannelList/hooks/listeners/useNewMessage.ts [hunk 1]
```diff
@@ -24,12 +26,26 @@ export const useNewMessage = <
...
+            });
+          }
+
+          // If channel doesn't exist in existing list, check in activeChannels as well.
+          // It may happen that channel was hidden using channel.hide(). In that case
+          // We remove it from `channels` state, but its still being watched and exists in client.activeChannels.
+          const channel = client.channel(event.channel_type, event.channel_id);
+
+          if (channel.initialized) {
+            return uniqBy([channel, ...channels], 'cid');
```
Comment (santhoshvai) [inline package/src/components/ChannelList/hooks/listeners/useNewMessage.ts:45]: `uniqBy([channel, ...channels], 'cid');`

the array doesnt have the hidden channel since the targetIndex was < 0, so `[channel, ...channels]` should suffice?

Comment (vishalnarkhede) [reply package/src/components/ChannelList/hooks/listeners/useNewMessage.ts:45]: You are right, pardon me for shameless copy&paste!!

**Review by santhoshvai — APPROVED** [review]
LGTM 👍

**Review by vanGalilea — APPROVED** [review]
