### PR TITLE
fix: add undefined check for message when checking for isMessageUnread

### LINKED ISSUE #2499: 🔥 [🐛] MessageList.tsx renderItem crash
## Issue

I am experiencing a crash originating from the MessageList.tsx -> renderItem -> isMessageRead method. The error:

```
cannot read property 'created_at' of undefined
```
Screenshot 2024-04-25 at 9 00 24 AM

### Steps to reproduce

I'm still investigating the steps to reproduce the issue. Not all channel members are affected.

### Expected behavior

The application should not crash.

## Project Related Information

React Native
react-native@0.72.3
stream-chat-expo@5.26.0

### Offline support

- [ x] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

## Environment

Production

#### `package.json`:

```json
# N/A
```

**`react-native info` output:**

info Fetching system and libraries information...
System:
  OS: macOS 14.0
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 309.04 MB / 16.00 GB
  Shell:
    version: 3.5.1
    path: /usr/local/bin/fish
Binaries:
  Node:
    version: 18.19.0
    path: ~/Library/Caches/fnm_multishells/86785_1714063943275/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.2.3
    path: ~/Library/Caches/fnm_multishells/86785_1714063943275/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/jmoyers/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK:
    API Levels:
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 30.0.3
      - 32.0.0
      - 33.0.0
    System Images:
      - android-31 | Google Play Intel x86 Atom_64
      - android-33 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.1 AI-221.6008.13.2211.9619390
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 18.0.2
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/jmoyers/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: ^0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [ ] Android
    - [ x] **iOS** but have not tested behavior on Android
    - [ ] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ x] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

### Additional context

I'll keep posting here as I learn more. It seems the index is out of bounds of the `processedMessagesArray` not sure if our custom code can impact this or not

Edit:

The issue goes away when we set `initialScrollToFirstUnreadMessage={false}`
```
<StreamChannel
            {...props}
            keyboardVerticalOffset={headerHeight}
            myMessageTheme={myMessageTheme}
            markdownRules={markdownRules}
            Message={Message}
            MessageSystem={MessageSystem}
            MessageAvatar={CustomAvatarWrapper}
            AutoCompleteSuggestionItem={AutoCompleteSuggestionItem}
            AutoCompleteSuggestionList={AutoCompleteSuggestionList}
            FileUploadPreview={FileUploadPreview}
            ImageUploadPreview={ImageUploadPreview}
            FileAttachment={FileAttachment}
            doDocUploadRequest={doDocUploadRequest}
            initialScrollToFirstUnreadMessage={true}
            NetworkDownIndicator={() => null}
            InlineUnreadIndicator={InlineUnreadIndicator}
        >
            {props.children}
        </StreamChannel>

```

### PR DESCRIPTION
**Pull request by khushal87**
## 🎯 Goal

Fixes #2499 

## 🎨 UI Changes

<details>
<summary>iOS</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

<details>
<summary>Android</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

## ☑️ Checklist

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] PR targets the `develop` branch
- [ ] Documentation is updated
- [ ] New code is tested in main example apps, including all possible scenarios
  - [ ] SampleApp iOS and Android
  - [ ] Expo iOS and Android

### CODE REVIEW

File: package/src/components/MessageList/MessageList.tsx [hunk 1]
```diff
@@ -612,14 +612,17 @@ const MessageListWithContext = <
...
       if (!isLatestMessageSetShown) {
+        const msg = processedMessageList?.[messageArrayIndex];
         if (
           channel.state.latestMessages.length !== 0 &&
           unreadCount > channel.state.latestMessages.length
         ) {
           return messageArrayIndex <= unreadCount - channel.state.latestMessages.length - 1;
-        } else if (lastRead && msg.created_at) {
+        }
+        // `msg` can be undefined here, hence we first check if its defined. Eg: `messageArrayIndex` is equal to processedMessageList.length.
```
Comment (santhoshvai) [inline package/src/components/MessageList/MessageList.tsx:624]: > `messageArrayIndex` is equal to processedMessageList.length.

This can never happen here as its under renderItem

Comment (santhoshvai) [reply package/src/components/MessageList/MessageList.tsx:624]: I think processedMessageList goes undefined while rendering happens or is changed

File: package/src/components/MessageList/MessageList.tsx [hunk 2]
```diff
@@ -612,14 +612,17 @@ const MessageListWithContext = <
...
+        else if (lastRead && msg && msg.created_at) {
```
Comment (santhoshvai) [inline package/src/components/MessageList/MessageList.tsx:625]:
```suggestion
        else if (lastRead && msg?.created_at) {
```
