### PR TITLE
fix: add copy and flag message action handler to actionHandlers

### LINKED ISSUE #2572: [🐛] missing flagMessage method in MessageActionHandlers provided to onLongPressMessage
## Issue

It seems like `MessageActionHandlers` interface has missing certain message actions like `flagMessage`. I need to have an access to that method from onLongPressMessage callback but for some reason it is not included.

Screenshot 2024-06-27 at 08 59 01

```tsx
<Channel
    onLongPressMessage={({ message, actionHandlers }) => {
      actionHandlers.flagMessage()  // <-- not available
    }}
>
      {children}
</Channel>
```

### PR DESCRIPTION
**Pull request by khushal87**
## 🎯 Goal

Fixes #2572

## 🎨 UI Changes

<details>
<summary>iOS</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

<details>
<summary>Android</summary>

<table>
    <thead>
        <tr>
            <td>Before</td>
            <td>After</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                
            </td>
            <td>
                
            </td>
        </tr>
    </tbody>
</table>
</details>

## ☑️ Checklist

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] PR targets the `develop` branch
- [ ] Documentation is updated
- [ ] New code is tested in main example apps, including all possible scenarios
  - [ ] SampleApp iOS and Android
  - [ ] Expo iOS and Android

### CODE REVIEW

File: package/src/components/Message/hooks/useMessageActionHandlers.ts [hunk 1]
```diff
@@ -84,6 +93,18 @@ export const useMessageActionHandlers = <
     setEditingState(message);
   };
 
+  const handleFlagMessage = async () => {
+    try {
+      await client.flagMessage(message.id);
+      Alert.alert(t('Message flagged'), t('The message has been reported to a moderator.'));
```
Comment (jakubdrozdek) [inline package/src/components/Message/hooks/useMessageActionHandlers.ts:99]: Is there a way to let the client decide how these messages are displayed? Using `Alert` from `react-native` might be inconsistent with the client UI for alerts and modals.

Comment (khushal87) [reply package/src/components/Message/hooks/useMessageActionHandlers.ts:99]: Hey @jakubdrozdek, right now we don't have an option to customize this. How important would it be for you?

**Review by santhoshvai — APPROVED** [review]
