### PR TITLE
fix: double check whether we scroll to an existing index when messageId is…

### LINKED ISSUE #2092: 🔥 MessageList throwing "scrollToIndex out of range" error causing a crash
## Issue

Describe your issue here

We are testing enabling hermes for Android with `react-native@0.70.9` and `stream-chat-react-native@5.13.0`. Testing around our app, we have a list of Pinned Messages where if you tap on one, [takes you to that message's scroll position](https://getstream.io/chat/docs/sdk/reactnative/core-components/channel/#messageid) in the `MessageList`. Intermittently the app has crashed. In 5-6 tries of doing the same thing, I had two crashes. Our DataDog reports the following:

message | scrollToIndex out of range: requested index 41 is out of 0 to 24
-- | --
stack | Invariant Violation: scrollToIndex out of range: requested index 41 is out of 0 to

[crash-reports.zip](https://github.com/GetStream/stream-chat-react-native/files/11433611/crash-reports.zip)

Interesting note: I do have your component wrapped in an error boundary, however it does not catch this error.

Screenshot_20230509-115504

---

### Steps to reproduce

1. We are testing enabling hermes for Android with `react-native@0.70.9`, `@react-navigation/stack@5.14.9` and `stream-chat-react-native@5.13.0`.
2. We have a Pinned Messages screen that lists the messages pinned for a channel. On tap of one, we have the user navigate back to a Conversation screen, passing the thread ID in route props and saving the tapped thread in context. We pass the saved thread as a prop to the `Channel` component which wraps the `MessageList` component. The intent is to have the `MessageList` scroll to the requested pinned message. 
3. Repeat a few times to replicate crash.

---

### Expected behavior

`MessageList` should scroll to desired thread and no crash on scroll failure.

---

### Customization

<details><summary>Click To Expand</summary>
<p>

```typescript jsx
// CONVERSATION SCREEN /////////
<StreamErrorBoundary
        message={getTranslation('messaging.errors.loadingConversation2', 1)}
        retryMessage={getTranslation('messaging.tapToRetry')}
        maxRetries={5}
      >
        <Channel<StreamChatGenerics>
          channel={channel}
          messageId={targetMessageId}
          formatDate={formatRelativeTime}
          keyboardVerticalOffset={headerHeight}
          thread={thread}
          AttachButton={AttachButton}
          CommandsButton={CommandsButton}
          SendButton={SendButton}
          InputReplyStateHeader={NoComponent}
          ReactionList={ReactionList}
          Message={Message}
          MessageSimple={MessageSimple}
          MessageSystem={MessageSystem}
          MessagePinnedHeader={MessagePinnedHeader}
          FileAttachmentIcon={FileIcon}
          MessageStatus={MessageStatus}
          messageActions={getMessageActions}
          onPressMessage={onPressMessage}
          onLongPressMessage={onLongPressMessage}
          doMarkReadRequest={doMarkReadRequest}
          supportedReactions={supportedReactions}
          EmptyStateIndicator={EmptyState}
          MessageAvatar={MessageAvatar}
          AutoCompleteSuggestionList={autoCompleteSuggestionList}
          AutoCompleteSuggestionHeader={autoCompleteSuggestionHeader}
        >
          <Container>
            <MessageList<StreamChatGenerics> />
            <MessageInput />
          </Container>
        </Channel>
      </StreamErrorBoundary>

// PINNED MESSAGES SCREEN ///////// - on press function
const onPress = (message: MessageResponse<StreamChatGenerics>) => () => {
    if (channel && channel.id) {
      setTimeout(() => {
        if (message) {
          setThread(message as MessageType<StreamChatGenerics>);
        }
      }, 0);
      navigation.push(MessagingRoute.Conversation, {
        channelId: channel.id,
        channelType: channel.type,
        targetMessageId: message.id,
      });
    }
  };
```
</p>
</details>

---

### Offline support

- [x] I have enabled offline support.
- [ ] The feature I'm having does not occur when offline support is disabled. (stripe out if not applicable)

---

## Environment

<details><summary>Click To Expand</summary>
<p>Pixel 6, Android 13

#### `package.json`:

```json
"react-native": "0.70.9",
"@stream-io/flat-list-mvcp": "0.10.2",
"stream-chat": "8.2.1",
"stream-chat-react-native": "5.13.0",
"@react-navigation/bottom-tabs": "5.11.15",
"@react-navigation/compat": "5.3.20",
"@react-navigation/material-top-tabs": "5.3.19",
"@react-navigation/native": "5.9.8",
"@react-navigation/stack": "5.14.9",
```

**`react-native info` output:**

```
 System:
    OS: macOS 13.3
    CPU: (10) x64 Apple M1 Pro
    Memory: 16.94 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.3/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
    Watchman: 2022.07.04.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.9862592
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.9 => 0.70.9 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
    - [ ] iOS
    - [x] Android
    - [ ] **iOS** but have not tested behavior on Android
    - [x] **Android** but have not tested behavior on iOS
    - [ ] Both
- **`stream-chat-react-native` version you're using that has this issue:**
    - `e.g. 5.4.3`
- Device/Emulator info:
  - [ ] I am using a physical device
  - OS version: `e.g. Android 10`
  - Device/Emulator: `e.g. iPhone 11`

</p>
</details>

---

### Additional context

---

### Screenshots

<details><summary>Click To Expand</summary>
<p>

</p>
</details>

---

### PR DESCRIPTION
**Pull request by vanGalilea**
fixes #2092 

## 🎯 Goal
Adding an extra layer of protection when scrolling to a specific `messageId`

## 🛠 Implementation details
Check whether index exists in flat list's data (message list) in order to prevent crashes

## 🎨 UI Changes
N/A

## 🧪 Testing
I haven't found a way to particularly reproduce this error, when testing please ensure that there is no regression by:
- fill in `messageId` param on `Channel` component with value `vir-c5155f18-cae5-4ba6-2686-06bdcd3427eb`
- run SampleApp
- open a channel with more than 100 messages
- click on user avatar and click on pinned messages and choose a pinned message
- validate that scrolling function and the chosen pinned message is visible

## ☑️ Checklist

- [ ] I have signed the [Stream CLA](https://docs.google.com/forms/d/e/1FAIpQLScFKsKkAJI7mhCr7K9rEIOpqIDThrWxuvxnwUq2XkHyG154vQ/viewform) (required)
- [ ] PR targets the `develop` branch
- [ ] Documentation is updated
- [ ] New code is tested in main example apps, including all possible scenarios
  - [ ] SampleApp iOS and Android
  - [ ] Expo iOS and Android

### CODE REVIEW

File: package/src/components/MessageList/MessageList.tsx [hunk 1]
```diff
@@ -784,27 +785,47 @@ const MessageListWithContext = <
   };
 
   const onScrollToIndexFailedRef = useRef<
-    FlatListProps<MessageType<StreamChatGenerics>>['onScrollToIndexFailed']
```
Comment (santhoshvai) [inline package/src/components/MessageList/MessageList.tsx:787]: why replace this typing?! its future proof

File: package/src/components/MessageList/MessageList.tsx [hunk 2]
```diff
@@ -784,27 +785,47 @@ const MessageListWithContext = <
...
+    });
+    // since we used only an average offset... we won't go to the center of the item yet
+    // with a little delay to wait for scroll to offset to complete, we can then scroll to the index
+    await new Promise((resolve) => setTimeout(resolve, WAIT_FOR_SCROLL_TO_OFFSET_TIMEOUT));
+
+    // We're checking if the index we're trying to scroll to, already exists in the messageList
+    // If it doesn't, we retry by calling onScrollToIndexFailedRef again
+    // Not doing this will result a crash that won't call onScrollToIndexFailed
+    if (
+      info.index > messageListLengthAfterUpdate - 1 &&
```
Comment (santhoshvai) [inline package/src/components/MessageList/MessageList.tsx:812]: we cannot use messageListLengthAfterUpdate inside useRef.. how does that work.. useRef is created only once..

Comment (santhoshvai) [reply package/src/components/MessageList/MessageList.tsx:812]: instead I would say its better to try catch the scrollToIndex and keep retrying for max 10 times or so

**Review by santhoshvai — CHANGES_REQUESTED** [review]
using messageListLengthAfterUpdate inside useRef is unfortunately buggy :(

File: package/src/components/MessageList/MessageList.tsx (hunk 1 above)
Comment (vanGalilea) [reply package/src/components/MessageList/MessageList.tsx:787]: I fully agree, yet I was not successful in extending this one with the optional `counter` arg

File: package/src/components/MessageList/MessageList.tsx [hunk 3]
```diff
@@ -783,28 +785,46 @@ const MessageListWithContext = <
...
+
+      if (messageIdLastScrolledToRef.current) {
+        setTargetedMessage(messageIdLastScrolledToRef.current);
+      }
+    } catch (e) {
+      if (
+        !onScrollToIndexFailedRef.current ||
+        scrollToIndexFailedRetryCountRef.current > MAX_RETRIES_AFTER_SCROLL_FAILURE
+      ) {
+        throw e;
```
Comment (santhoshvai) [inline package/src/components/MessageList/MessageList.tsx:820]: my view is that we shouldnt throw here..

lets just gracefully log the error

The error we may get is index not found in the array.. which means we cant scroll to it..

we dont need to throw an error for that.. it may be uncatched the integrator

File: package/src/components/MessageList/MessageList.tsx [hunk 4]
```diff
@@ -783,28 +785,47 @@ const MessageListWithContext = <
...
+
+      if (messageIdLastScrolledToRef.current) {
+        setTargetedMessage(messageIdLastScrolledToRef.current);
+      }
+    } catch (e) {
+      if (
+        !onScrollToIndexFailedRef.current ||
+        scrollToIndexFailedRetryCountRef.current > MAX_RETRIES_AFTER_SCROLL_FAILURE
+      ) {
+        console.log('Scrolling to index failed after 10 retries', e);
```
Comment (santhoshvai) [inline package/src/components/MessageList/MessageList.tsx:820]:
```suggestion
        console.log(`Scrolling to index failed after ${MAX_RETRIES_AFTER_SCROLL_FAILURE} retries`, e);
```

File: package/src/components/MessageList/MessageList.tsx [hunk 5]
```diff
@@ -783,28 +785,47 @@ const MessageListWithContext = <
     }
   };
 
+  const scrollToIndexFailedRetryCountRef = useRef<number>(0);
```
Comment (santhoshvai) [inline package/src/components/MessageList/MessageList.tsx:788]: we should reset this to 0 at some point! 

maybe whenever scrollTo() is called

**Review by santhoshvai — CHANGES_REQUESTED** [review]
requesting changes for the reset to 0

**Review by santhoshvai — APPROVED** [review]
